name: Run Google Tests

on:
  push:
    branches:
      - main  # Укажите здесь вашу основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: 'CMakeLists.txt'
        buildDirectory: 'build'

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        ./test_B
