name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run:
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        echo "_____________something_____________"
